# File: /srv/appdata/prometheus/prometheus.yml

global:
  # How often should Prometheus scrape metrics from each source
  scrape_interval: 15s 
  external_labels:
    # The following label is useful to have in Grafana for multi-server dashboards
    monitor: 'HOSTNAME'

remote_write:
  # Address of the server running the prometheus aggregation service
  - url: 'http://REMOTE_HOST/api/v1/write'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'process-exporter'
    static_configs:
      - targets: ['process-exporter:9256']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']