http:
  middlewares:
    securityHeaders:
      headers:
        customResponseHeaders:
          server: ""
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "strict-origin-when-cross-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
    # Add to sites that do not want their content indexed by search engines (e.g. Google)
    noIndexHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "noindex,nofollow"
    # Add to sites where Authelia auth needs to be applied by Traefik itself
    authelia:
      forwardauth:
        # address: ==> Use $TRAEFIK_HTTP_MIDDLEWARES_AUTH_FORWARDAUTH_ADDRESS ("http://authelia:9091/api/verify?rd=https://auth.example.com/")
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email