# File: /srv/appdata/prometheus/prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'process-exporter'
    static_configs:
      - targets: ['process-exporter:9256']
  - job_name: 'smartctl-exporter'
    static_configs:
      - targets: ['smartctl-exporter:9633']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']