# File: /srv/appdata/prometheus/prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
    relabel_configs:
      # The following label is useful to have in Grafana for multi-server dashboards
      - replacement: 'HOSTNAME'
        target_label: monitor
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      # The following label is useful to have in Grafana for multi-server dashboards
      - replacement: 'HOSTNAME'
        target_label: monitor
  - job_name: 'process-exporter'
    static_configs:
      - targets: ['process-exporter:9256']
    relabel_configs:
      # The following label is useful to have in Grafana for multi-server dashboards
      - replacement: 'HOSTNAME'
        target_label: monitor
  - job_name: 'smartctl-exporter'
    static_configs:
      - targets: ['smartctl-exporter:9633']
    relabel_configs:
      # The following label is useful to have in Grafana for multi-server dashboards
      - replacement: 'HOSTNAME'
        target_label: monitor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      # The following label is useful to have in Grafana for multi-server dashboards
      - replacement: 'HOSTNAME'
        target_label: monitor