# The services that make up our stack

services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    network_mode: host
    command: ['tunnel', '--no-autoupdate', 'run', '--token', '${CF_TOKEN}']