name: Generate Portainer Templates

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Merge Templates
        run: |
          echo '{"version": "3", "templates": []}' > templates.json  # Initialize JSON structure
          
          find . -name "template.json" -not -path "./templates.json" | while read file; do
            dir=$(dirname "$file")  # Get the directory of the template.json
      
            # Read and format the notes.html file if it exists
            if [ -f "$dir/notes.html" ]; then
              note=$(cat "$dir/notes.html" | jq -Rs '.')  # Read file, escape newlines properly
            else
              note="null"
            fi
      
            # Merge the template with the note
            jq --arg note "$note" '. + { note: $note }' "$file" > tmp.json
            
            # Append to the "templates" array
            jq '.templates += [input]' templates.json tmp.json > merged.json && mv merged.json templates.json
          done

      - name: Upload to GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          name: templates
          path: templates.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download templates.json
        uses: actions/download-artifact@v4
        with:
          name: templates
          path: .

      - name: Deploy to gh-pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          git add templates.json
          git commit -m "Update Portainer Templates"
          git push -f origin gh-pages